### ISSUE TITLE
[Feature] 정답과 오답의 양식이 너무 다른 것 같습니다

### ISSUE THREAD

**Issue by jaewooklee93** [swsnu/swpp2020-team18#18]
![image](https://user-images.githubusercontent.com/11328376/101761690-cdefc580-3b1f-11eb-94e2-e0585ac7d2f4.png)

정답과 가짜 오답들의 양식 차이 때문에 잘 몰라도 답을 맞출 수 있는 상황인 것 같습니다

**Comment by SPICYJO** [comment]
Resolved
