### ISSUE TITLE
[Feature] statistics

### ISSUE THREAD

**Issue by jiyewise** [swsnu/swpp2020-team18#19]
오늘 처음으로 테스트를 했는데 statistics graph에서 테스팅 안한 날도 점수가 있는데 mock data 인가요?

**Comment by jiyewise** [comment]
<img width="1092" alt="Screen Shot 2020-12-10 at 7 44 14 PM" src="https://user-images.githubusercontent.com/67668461/101761915-16a77e80-3b20-11eb-81b2-d1a6d6c75803.png">

**Comment by SPICYJO** [comment]
네, 저번 discussion session에서는 mock data를 입력해두었습니다. 현재는 mock data를 제외시켜놓았습니다.
