### ISSUE TITLE
[Bug] sign up & sign in 안됨

### ISSUE THREAD

**Issue by helkw** [swsnu/swpp2020-team18#20]
**Describe the bug**
signup과 signin 버튼이 동작하지 않습니다.

**To Reproduce**
1. signup에서 signup버튼 누르기
2. signin으로 돌아와서 signin 버튼 누르기

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SPICYJO** [comment]
Duplicate of issue #21
