### ISSUE TITLE
[Bug] 찾아낸 버그들

### ISSUE THREAD

**Issue by ChanwooLucioLee** [swsnu/swpp2020-team18#21]
1. https://term-inator.site/signin#에서 Forgot Passowrd? 눌러도 아무 반응 없음

2. https://term-inator.site/signup에서 Sign up이 안 됨. 그래서 이후 기능들 사용이 어려움.
 sign up에서 에러가 나는 이유(에러 메시지)가 나오면 고칠텐데 안 떠서 모르겠음.

**Comment by SPICYJO** [comment]
Resolved in commit 6d1ea4af1860f45fe512e12974d2cddece7d6dc8
