### ISSUE TITLE
[Feature] article 단어 퀴즈

### ISSUE THREAD

**Issue by jiyewise** [swsnu/swpp2020-team18#22]
**Feature description**

article recommendation에서 기사를 읽으면서 단어 문제를 풀 때 한 문제를 풀고 next를 누르면 바로 답이 떴으면 좋겠습니다 (맞았는지, 틀렸으면 정답이 뭔지)
기사를 읽으면서 모르는 단어가 있어 문제를 풀어도 단어 뜻을 쭉 모르는 상태로 읽는 것보다 단어 뜻을 잘 알고 읽는 게 낫지 않나 싶어서요!

그리고 답을 다 틀리게 해도 다음 article로 넘어가는데, 퀴즈 정답을 알려주셨으면 좋겠습니다

**Comment by jiyewise** [comment]
비슷한 맥락으로 리뷰 테스트가 끝나도 답을 안 알려줘서 테스트를 해도 학습 효과가 있을지 의문입니다..!

**Comment by SPICYJO** [comment]
Article 퀴즈를 보고나서 결과를 확인할 수 있는 페이지를 추가하였습니다. 정답/오답 확인 및 본인의 점수를 확인할 수 있습니다. 리뷰 테스트도 마찬가지로 구현을 하였습니다. 좋은 피드백 감사합니다!
